# Generated by Django 3.2.9 on 2021-12-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0002_alter_books_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['author']},
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteka.author'),
        ),
    ]
