# Generated by Django 3.2.9 on 2021-12-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0003_auto_20211201_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteka.genre'),
        ),
    ]
