# Generated by Django 3.2.9 on 2021-12-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0004_auto_20211201_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowed',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteka.books'),
        ),
    ]
