# Generated by Django 3.2.9 on 2021-12-08 15:53

import Biblioteka.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0006_user_of_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_of_library',
            name='date_of_end',
            field=models.DateField(default=Biblioteka.models.date_doom),
        ),
    ]
