# Generated by Django 3.2.9 on 2021-12-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Biblioteka', '0007_alter_user_of_library_date_of_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
