# Generated by Django 3.2.9 on 2021-12-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0008_borrowed_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='group',
        ),
    ]
